### ISSUE TITLE
TemporalParser produces tomorrow night for "tonight"

### ISSUE THREAD

**Issue by rfriel** [digamma-ai/timeextractor#5]
In `TemporalParser.getRelativeTemporalObjectByProperty` there is [the following block](https://github.com/digamma-ai/timeextractor/blob/master/src/main/java/ai/digamma/utils/TemporalParser.java#L229):

```java
        if (property.equalsIgnoreCase("tonight")) {
            localDate = localDate.plusDays(1);
            TimeDate timeDate = Utils.getTimeDateUTC(localDate);
            Time time = new Time(19, 0, 0);
            time.setTimezone(0);

            timeDate.setTime(time);

            return TemporalObjectGenerator.generateTemporalTime(Type.DATE, timeDate);
        }
```

The line `localDate = localDate.plusDays(1);` incorrectly moves the date to tomorrow.  As a result, `ExtractionService.extract("tonight", settings)` returns start and end dates one day after the date in `settings`.

A related but smaller issue: it seems like the time-of-day cases in `TemporalParser.getRelativeTemporalObjectByProperty` should behave the same way as those in `TemporalParser.getTimeOfDay`, returning a `TIME_INTERVAL` spanning part of the day.

Instead, they currently return a `DATE` corresponding to a particular hour in the day.  (So, for example, the string "night" is extracted as 10PM to midnight on the user date, while the string "tonight" is extracted as precisely 9PM on the user date.)

**Comment by vzaliva** [comment]
we will be glad to accept Pull Request with the fix!

**Comment by alex-balandin** [comment]
Generating of Temporal object by "tonight" property is fixed.
